import type {
  ActivityItem,
  CategoryBattle,
  Forecast,
  SchoolLeaderboard,
  ScoutProfile,
  Startup,
} from "./types";

export const DEMO_DISCLAIMER =
  "Simulated MVP — no real money, no real investing. Campus rivalry & capital are mock data.";

export const FUND_GOAL = {
  target: "$10M student-powered fund",
  contributors: "100,000 students × $100",
  perks: [
    "Earlier contributors get higher voting weight",
    "Recruit friends to boost your scout influence",
    "Top forecasters earn reputation + stronger votes",
  ],
};

export const CURRENT_SCOUT: ScoutProfile = {
  id: "user-1",
  name: "Alex Chen",
  school: "Stanford",
  year: "Junior",
  major: "CS + Symbolic Systems",
  avatar: "AC",
  tier: "Deal Captain",
  startupsDiscovered: 8,
  recruitCount: 14,
  votingWeight: 1.4,
  forecastAccuracy: 78,
  simulatedCapital: 10000,
  allocated: 3200,
  rank: 12,
  forecasts: 24,
  wins: 14,
};

export const rivalryTicker = [
  "Stanford is leading AI dealflow",
  "Berkeley scouts are climbing",
  "MIT has the highest forecast accuracy",
  "USC just backed a dorm-room unicorn",
  "Penn pipeline heating up in fintech",
  "Harvard scouts are early on Pulse Health",
];

export const schoolLeaderboard: SchoolLeaderboard[] = [
  {
    rank: 1,
    school: "Stanford",
    shortName: "Stanford",
    emoji: "🌲",
    color: "from-red-500/30 to-cardinal-500/10",
    totalCapitalAllocated: 2_840_000,
    startupsSubmitted: 34,
    forecastAccuracy: 81,
    activeScouts: 1240,
    topBackedStartup: "Synapse AI",
    rivalryCopy: "Stanford is leading AI dealflow",
  },
  {
    rank: 2,
    school: "MIT",
    shortName: "MIT",
    emoji: "🔬",
    color: "from-rose-500/30 to-red-900/10",
    totalCapitalAllocated: 2_610_000,
    startupsSubmitted: 28,
    forecastAccuracy: 89,
    activeScouts: 980,
    topBackedStartup: "Synapse AI",
    rivalryCopy: "MIT has the highest forecast accuracy",
  },
  {
    rank: 3,
    school: "UC Berkeley",
    shortName: "Berkeley",
    emoji: "🐻",
    color: "from-amber-500/30 to-blue-600/10",
    totalCapitalAllocated: 2_420_000,
    startupsSubmitted: 31,
    forecastAccuracy: 76,
    activeScouts: 1105,
    topBackedStartup: "GreenLoop",
    rivalryCopy: "Berkeley scouts are climbing",
  },
  {
    rank: 4,
    school: "Harvard",
    shortName: "Harvard",
    emoji: "🎓",
    color: "from-crimson-500/30 to-rose-900/10",
    totalCapitalAllocated: 2_180_000,
    startupsSubmitted: 22,
    forecastAccuracy: 84,
    activeScouts: 890,
    topBackedStartup: "Pulse Health",
    rivalryCopy: "Harvard scouts are early on health tech",
  },
  {
    rank: 5,
    school: "UCLA",
    shortName: "UCLA",
    emoji: "💙",
    color: "from-blue-500/30 to-yellow-500/10",
    totalCapitalAllocated: 1_920_000,
    startupsSubmitted: 19,
    forecastAccuracy: 72,
    activeScouts: 760,
    topBackedStartup: "CourseLift",
    rivalryCopy: "Rising at UCLA",
  },
  {
    rank: 6,
    school: "USC",
    shortName: "USC",
    emoji: "✌️",
    color: "from-amber-400/30 to-cardinal-600/10",
    totalCapitalAllocated: 1_740_000,
    startupsSubmitted: 17,
    forecastAccuracy: 70,
    activeScouts: 680,
    topBackedStartup: "SnackMatch",
    rivalryCopy: "USC consumer deals trending",
  },
  {
    rank: 7,
    school: "Penn",
    shortName: "Penn",
    emoji: "🦁",
    color: "from-blue-700/30 to-red-600/10",
    totalCapitalAllocated: 1_580_000,
    startupsSubmitted: 15,
    forecastAccuracy: 74,
    activeScouts: 620,
    topBackedStartup: "VaultPay",
    rivalryCopy: "Penn fintech scouts gaining ground",
  },
  {
    rank: 8,
    school: "NYU",
    shortName: "NYU",
    emoji: "🗽",
    color: "from-violet-500/30 to-purple-900/10",
    totalCapitalAllocated: 1_410_000,
    startupsSubmitted: 14,
    forecastAccuracy: 71,
    activeScouts: 540,
    topBackedStartup: "VaultPay",
    rivalryCopy: "NYU scouts active in consumer fintech",
  },
];

export const categoryBattles: CategoryBattle[] = [
  {
    id: "ai",
    title: "Best AI Startup Pipeline",
    leadingSchool: "Stanford",
    runnerUp: "MIT",
    leaderStat: "12 AI deals scouted",
    copy: "Stanford vs MIT — the brain battle",
  },
  {
    id: "consumer",
    title: "Best Consumer Startup Pipeline",
    leadingSchool: "USC",
    runnerUp: "UCLA",
    leaderStat: "9 consumer hits this month",
    copy: "SoCal consumer crown up for grabs",
  },
  {
    id: "technical",
    title: "Best Technical Founders",
    leadingSchool: "MIT",
    runnerUp: "Stanford",
    leaderStat: "94 avg technical score",
    copy: "MIT Technical Edge holding strong",
  },
  {
    id: "forecasters",
    title: "Best Forecasters",
    leadingSchool: "MIT",
    runnerUp: "Harvard",
    leaderStat: "89% accuracy",
    copy: "Prediction market kings",
  },
  {
    id: "scouts",
    title: "Most Active Scouts",
    leadingSchool: "Stanford",
    runnerUp: "UC Berkeley",
    leaderStat: "1,240 active scouts",
    copy: "Stanford never sleeps on dealflow",
  },
  {
    id: "gems",
    title: "Best Hidden Gems",
    leadingSchool: "UC Berkeley",
    runnerUp: "Penn",
    leaderStat: "6 pre-hype backs",
    copy: "Berkeley finds them before YC",
  },
];

export const scouts: ScoutProfile[] = [
  {
    id: "inv-1",
    name: "Sofia Martinez",
    school: "Stanford",
    year: "Senior",
    major: "Economics",
    avatar: "SM",
    tier: "Superforecaster",
    startupsDiscovered: 19,
    recruitCount: 42,
    votingWeight: 2.1,
    forecastAccuracy: 92,
    simulatedCapital: 10000,
    allocated: 8900,
    rank: 1,
    forecasts: 41,
    wins: 32,
  },
  {
    id: "inv-2",
    name: "Ryan Park",
    school: "MIT",
    year: "Junior",
    major: "EECS",
    avatar: "RP",
    tier: "Campus Partner",
    startupsDiscovered: 16,
    recruitCount: 38,
    votingWeight: 1.9,
    forecastAccuracy: 89,
    simulatedCapital: 10000,
    allocated: 7600,
    rank: 2,
    forecasts: 38,
    wins: 28,
  },
  {
    id: "inv-3",
    name: "Nina Okonkwo",
    school: "Harvard",
    year: "Senior",
    major: "Applied Math",
    avatar: "NO",
    tier: "Superforecaster",
    startupsDiscovered: 14,
    recruitCount: 29,
    votingWeight: 1.8,
    forecastAccuracy: 86,
    simulatedCapital: 10000,
    allocated: 8200,
    rank: 3,
    forecasts: 35,
    wins: 26,
  },
  {
    id: "inv-4",
    name: "Alex Chen",
    school: "Stanford",
    year: "Junior",
    major: "CS + Symbolic Systems",
    avatar: "AC",
    tier: "Deal Captain",
    startupsDiscovered: 8,
    recruitCount: 14,
    votingWeight: 1.4,
    forecastAccuracy: 78,
    simulatedCapital: 10000,
    allocated: 3200,
    rank: 12,
    forecasts: 24,
    wins: 14,
  },
  {
    id: "inv-5",
    name: "Jordan Kim",
    school: "UC Berkeley",
    year: "Sophomore",
    major: "Data Science",
    avatar: "JK",
    tier: "Deal Captain",
    startupsDiscovered: 11,
    recruitCount: 22,
    votingWeight: 1.5,
    forecastAccuracy: 84,
    simulatedCapital: 10000,
    allocated: 5400,
    rank: 4,
    forecasts: 31,
    wins: 22,
  },
  {
    id: "inv-6",
    name: "Emily Zhang",
    school: "UCLA",
    year: "Junior",
    major: "Business",
    avatar: "EZ",
    tier: "Campus Analyst",
    startupsDiscovered: 7,
    recruitCount: 18,
    votingWeight: 1.2,
    forecastAccuracy: 81,
    simulatedCapital: 10000,
    allocated: 6100,
    rank: 5,
    forecasts: 29,
    wins: 20,
  },
];

export const startups: Startup[] = [
  {
    id: "synapse-ai",
    name: "Synapse AI",
    tagline: "Copilot for research labs",
    description:
      "Synapse AI automates literature review, experiment design, and data analysis for university research teams.",
    sector: "AI",
    campus: "MIT",
    founderName: "Priya Sharma",
    founders: ["Priya Sharma", "James Okonkwo"],
    campusTag: "MIT · Lab-to-Launch",
    stage: "Seed",
    askAmount: 500000,
    valuation: 8000000,
    logoEmoji: "🧠",
    gradient: "from-cyan-500/20 via-violet-500/20 to-emerald-500/20",
    metrics: { mrr: 42000, users: 340, growth: "+28% MoM" },
    forecastScore: 87,
    aiMemoScore: 91,
    totalVotes: 156,
    bullishPercent: 72,
    fundedAmount: 180000,
    targetRaise: 500000,
    createdAt: "2025-03-12",
    trendingLabel: "MIT Technical Edge",
    isTrending: true,
    schoolBackers: [
      { school: "MIT", scoutCount: 58, momentum: "leading" },
      { school: "Stanford", scoutCount: 42, momentum: "rising" },
      { school: "Harvard", scoutCount: 19, momentum: "early" },
    ],
    socialProof: [
      "Backed by 42 Stanford students",
      "MIT scouts are early",
      "Hot deal on campus",
    ],
    aiMemo:
      "Strong product-market fit signals in academic R&D. Recurring revenue from 12 university departments.",
  },
  {
    id: "greenloop",
    name: "GreenLoop",
    tagline: "Circular economy for dorm move-out",
    description:
      "GreenLoop connects students selling furniture during move-out with incoming freshmen.",
    sector: "Climate",
    campus: "UC Berkeley",
    founderName: "Maya Rodriguez",
    founders: ["Maya Rodriguez"],
    campusTag: "Berkeley · Sustainability",
    stage: "Pre-seed",
    askAmount: 150000,
    valuation: 2000000,
    logoEmoji: "♻️",
    gradient: "from-emerald-500/20 via-teal-500/20 to-cyan-500/20",
    metrics: { users: 2400, growth: "+45% semester" },
    forecastScore: 74,
    aiMemoScore: 78,
    totalVotes: 98,
    bullishPercent: 65,
    fundedAmount: 62000,
    targetRaise: 150000,
    createdAt: "2025-04-02",
    trendingLabel: "Berkeley Momentum",
    isTrending: true,
    schoolBackers: [
      { school: "UC Berkeley", scoutCount: 67, momentum: "leading" },
      { school: "Stanford", scoutCount: 28, momentum: "rising" },
      { school: "UCLA", scoutCount: 15, momentum: "early" },
    ],
    socialProof: [
      "Berkeley scouts are climbing",
      "Trending on Campus",
      "Backed by 67 Berkeley students",
    ],
  },
  {
    id: "pulsehealth",
    name: "Pulse Health",
    tagline: "Mental health triage for campus clinics",
    description:
      "AI-powered intake that routes students to the right level of care at campus health centers.",
    sector: "Health",
    campus: "Harvard",
    founderName: "David Kim",
    founders: ["David Kim", "Sarah O'Brien"],
    campusTag: "Harvard · Health Tech",
    stage: "Seed",
    askAmount: 750000,
    valuation: 12000000,
    logoEmoji: "💚",
    gradient: "from-rose-500/20 via-violet-500/20 to-cyan-500/20",
    metrics: { mrr: 68000, users: 8900, growth: "+22% MoM" },
    forecastScore: 91,
    aiMemoScore: 94,
    totalVotes: 203,
    bullishPercent: 81,
    fundedAmount: 410000,
    targetRaise: 750000,
    createdAt: "2025-02-18",
    trendingLabel: "Dorm-Room Unicorn",
    isTrending: true,
    schoolBackers: [
      { school: "Harvard", scoutCount: 51, momentum: "leading" },
      { school: "MIT", scoutCount: 38, momentum: "early" },
      { school: "Penn", scoutCount: 24, momentum: "rising" },
    ],
    socialProof: [
      "Harvard scouts are early",
      "YC-Bait",
      "Backed by 51 Harvard students",
    ],
    aiMemo:
      "Exceptional traction with 3 pilot universities converting to paid.",
  },
  {
    id: "courselift",
    name: "CourseLift",
    tagline: "Peer tutoring marketplace",
    description:
      "Students book verified tutors from their own university for specific courses.",
    sector: "EdTech",
    campus: "UCLA",
    founderName: "Jordan Lee",
    founders: ["Jordan Lee", "Emily Park"],
    campusTag: "UCLA · Campus Marketplace",
    stage: "Pre-seed",
    askAmount: 200000,
    valuation: 2500000,
    logoEmoji: "📚",
    gradient: "from-amber-500/20 via-orange-500/20 to-rose-500/20",
    metrics: { users: 1200, growth: "+18% MoM" },
    forecastScore: 68,
    aiMemoScore: 72,
    totalVotes: 67,
    bullishPercent: 58,
    fundedAmount: 45000,
    targetRaise: 200000,
    createdAt: "2025-04-15",
    trendingLabel: "Rising at UCLA",
    isTrending: false,
    schoolBackers: [
      { school: "UCLA", scoutCount: 44, momentum: "leading" },
      { school: "USC", scoutCount: 22, momentum: "rising" },
    ],
    socialProof: ["Rising at UCLA", "Backed by 44 UCLA students"],
  },
  {
    id: "vaultpay",
    name: "VaultPay",
    tagline: "Split bills for student orgs",
    description:
      "Treasury management for clubs and Greek life—collect dues and forecast budgets.",
    sector: "Fintech",
    campus: "NYU",
    founderName: "Marcus Williams",
    founders: ["Marcus Williams"],
    campusTag: "NYU · Student Fintech",
    stage: "Seed",
    askAmount: 400000,
    valuation: 6000000,
    logoEmoji: "💳",
    gradient: "from-blue-500/20 via-indigo-500/20 to-violet-500/20",
    metrics: { mrr: 31000, users: 5200, growth: "+35% MoM" },
    forecastScore: 79,
    aiMemoScore: 82,
    totalVotes: 124,
    bullishPercent: 69,
    fundedAmount: 195000,
    targetRaise: 400000,
    createdAt: "2025-03-28",
    trendingLabel: "Penn Pipeline Pick",
    isTrending: true,
    schoolBackers: [
      { school: "Penn", scoutCount: 36, momentum: "leading" },
      { school: "NYU", scoutCount: 31, momentum: "leading" },
      { school: "Stanford", scoutCount: 18, momentum: "early" },
    ],
    socialProof: [
      "Penn pipeline heating up",
      "Hot Among Stanford Scouts",
      "Backed by 36 Penn students",
    ],
    aiMemo: "Sticky B2B2C model through student organizations.",
  },
  {
    id: "snackmatch",
    name: "SnackMatch",
    tagline: "Late-night food discovery on campus",
    description:
      "TikTok-style feed of what's open, deals, and group orders near you.",
    sector: "Consumer",
    campus: "USC",
    founderName: "Tyler Nguyen",
    founders: ["Tyler Nguyen", "Aisha Patel"],
    campusTag: "USC · Consumer",
    stage: "Pre-seed",
    askAmount: 100000,
    valuation: 1500000,
    logoEmoji: "🍕",
    gradient: "from-orange-500/20 via-red-500/20 to-pink-500/20",
    metrics: { users: 890, growth: "+52% MoM" },
    forecastScore: 71,
    aiMemoScore: 75,
    totalVotes: 89,
    bullishPercent: 63,
    fundedAmount: 38000,
    targetRaise: 100000,
    createdAt: "2025-05-01",
    trendingLabel: "Trending on Campus",
    isTrending: true,
    schoolBackers: [
      { school: "USC", scoutCount: 52, momentum: "leading" },
      { school: "UCLA", scoutCount: 29, momentum: "rising" },
    ],
    socialProof: [
      "USC consumer deals trending",
      "Hot deal on campus",
      "Backed by 52 USC students",
    ],
  },
];

export const forecasts: Forecast[] = [
  { id: "f-1", startupId: "pulsehealth", investorId: "user-1", direction: "bullish", confidence: 85, allocation: 500, createdAt: "2025-05-10" },
  { id: "f-2", startupId: "synapse-ai", investorId: "user-1", direction: "bullish", confidence: 72, allocation: 300, createdAt: "2025-05-08" },
  { id: "f-3", startupId: "vaultpay", investorId: "user-1", direction: "bearish", confidence: 60, allocation: 200, createdAt: "2025-05-05" },
];

export const activities: ActivityItem[] = [
  { id: "a-1", type: "rivalry", message: "Stanford overtook Berkeley in AI dealflow", timestamp: "12m ago" },
  { id: "a-2", type: "memo", message: "AI memo generated for Pulse Health", timestamp: "2h ago" },
  { id: "a-3", type: "forecast", message: "You went bullish on Synapse AI ($300)", timestamp: "1d ago" },
  { id: "a-4", type: "fund", message: "42 Stanford scouts backed Synapse AI", timestamp: "2d ago" },
];

export const CURRENT_USER = CURRENT_SCOUT;
export const investors = scouts;

export function getStartupById(id: string): Startup | undefined {
  return startups.find((s) => s.id === id);
}

export function getScoutById(id: string): ScoutProfile | undefined {
  return scouts.find((s) => s.id === id);
}

export function formatCurrency(amount: number): string {
  if (amount >= 1_000_000) return `$${(amount / 1_000_000).toFixed(1)}M`;
  if (amount >= 1_000) return `$${(amount / 1_000).toFixed(0)}K`;
  return `$${amount}`;
}
